"""Gear item illustrations: one generic image per item category (deduped). Images live in assets/items/<key>.webp."""
import re
# (regex on label/query, key, subject for the prompt). First match wins; order specific -> general.
RULES = [
 (r"spotting scope", "spotting-scope", "a spotting scope on a short tripod"),
 (r"glassing tripod", "tripod", "a sturdy glassing tripod"),
 (r"neoprene", "dog-vest", "a hunting retriever dog wearing a neoprene vest"),
 (r"dog training whistle|dog whistle", "whistle", ""),
 (r"dog blaze", "dog-orange-vest", "a hunting dog wearing a blaze orange vest"),
 (r"dog first aid", "dog-first-aid", "a dog first-aid kit"),
 (r"dog boots", "dog-boots", "dog boots"),
 (r"training dumm", "dummies", "retriever training dummies"),
 (r"dog stand", "dog-stand", "a dog stand platform in a marsh"),
 (r"gps dog", "dog-gps", "a dog GPS tracking collar"),
 (r"binocular harness", "binocular-harness", "a chest harness pouch for binoculars"),
 (r"binocular", "binoculars", "a pair of hunting binoculars"),
 (r"laser rangefinder|^rangefinder", "rangefinder", "a compact handheld laser rangefinder"),
 (r"lens clean", "lens-cleaning", "a lens cleaning pen and microfiber cloth"),
 (r"scope cover", "scope-covers", "flip-up lens covers for a riflescope, shown alone"),
 (r"merino|base layer|layering|wool layers|warm layer|fleece", "base-layers", "folded merino wool base layer shirt and leggings"),
 (r"insulated.*jacket|loden|attire", "jacket", "an insulated hunting jacket in olive and khaki"),
 (r"\brain\b", "rain-gear", "a packable rain jacket and pants"),
 (r"rubber knee", "rubber-boots", "tall rubber knee boots"),
 (r"insulated waterproof|waterproof hunting boots|mountain boots|broken-in|hunting boots|hiking boots|lightweight hunting boots", "boots", "a pair of rugged leather hunting boots"),
 (r"blaze orange|orange hat", "blaze-orange", "a blaze orange vest and hat"),
 (r"socks", "wool-socks", "thick wool hunting socks"),
 (r"drag rope", "drag-rope", "a deer drag rope harness"),
 (r"field dressing gloves", "dressing-gloves", "long protective field dressing gloves"),
 (r"face mask|gloves", "face-mask-gloves", "a camo face mask and thin gloves"),
 (r"gaiter", "gaiters", "a pair of hiking gaiters"),
 (r"khaki hunting shirt", "safari-clothing", "neutral khaki safari shirt and trousers, folded"),
 (r"wide brim|sunglasses", "hat-sunglasses", "a wide-brim hat with sunglasses"),
 (r"scent control hunting clothing", "scent-layers", "neatly folded hunting layers in a sealed tote"),
 (r"safety harness|lifeline", "safety-harness", "a full-body tree stand safety harness with a tether"),
 (r"pull up rope|pull-up rope", "pull-up-rope", "a coiled pull-up rope with a carabiner"),
 (r"seat cushion|hunting seat", "seat-cushion", "a foam hunting seat cushion"),
 (r"hang on tree stand", "hang-on-stand", "a hang-on tree stand strapped to a tree trunk"),
 (r"ladder stand", "ladder-stand", "a ladder tree stand against a tree"),
 (r"climbing tree stand", "climbing-stand", "a climbing tree stand on a straight tree"),
 (r"ground blind", "ground-blind", "a pop-up hunting ground blind in the woods"),
 (r"bow sling", "bow-sling", "a bow sling strap"),
 (r"accessory hooks|bow holder", "stand-hooks", "screw-in gear hooks and a bow holder"),
 (r"grunt call|rattling", "deer-calls", "a deer grunt call and rattling antlers"),
 (r"box call|turkey calls? box|^turkey calls?\b", "turkey-box-call", "a wooden turkey box call"),
 (r"slate|pot call", "turkey-slate-call", "a round turkey slate call with a striker"),
 (r"diaphragm|mouth call", "turkey-mouth-calls", "small diaphragm turkey mouth calls in a case"),
 (r"\bowl\b|\bcrow\b|locator", "locator-calls", "owl and crow locator calls"),
 (r"duck goose call|duck call", "duck-call", "a wooden duck call on a lanyard"),
 (r"goose call", "goose-call", "a short-reed goose call"),
 (r"duck decoys", "duck-decoys", "duck decoys floating with anchor weights"),
 (r"turkey decoys", "turkey-decoys", "a hen turkey decoy in a field"),
 (r"elk bugle|cow call", "elk-calls", "an elk bugle tube and a cow call"),
 (r"predator call", "predator-call", "a handheld predator call"),
 (r"motion decoy", "motion-decoy", "a small predator motion decoy on a stake"),
 (r"moose call", "moose-call", "a birch-bark style moose call cone"),
 (r"wind checker", "wind-checker", "a squeeze bottle releasing a puff of wind-checker powder"),
 (r"scent elimination|scent free body|scent free laundry|scent-free", "scent-spray", "an unbranded spray bottle and wash bottle"),
 (r"storage bag|tote", "scent-tote", "a sealed clothing storage tote"),
 (r"cover scent", "cover-scent", "a small unlabeled scent bottle on a log"),
 (r"archery target", "archery-target", "a foam archery block target with arrows"),
 (r"release aid", "release-aid", "a bow release aid"),
 (r"bow case", "bow-case", "a padded bow case"),
 (r"broadhead wrench|archery.*tool", "archery-tools", "archery tools: broadhead wrench and hex keys"),
 (r"broadhead case|broadheads", "broadheads", "a closed broadhead storage case"),
 (r"quiver", "quiver", "a bow quiver holding arrows"),
 (r"mount lock box|trail camera mount", "cam-mount", "a trail camera security box and mount"),
 (r"hard rifle case", "hard-case", "a lockable hard gun case, closed"),
 (r"soft rifle case", "soft-case", "a padded soft long-gun case, closed"),
 (r"rifle sling", "sling", "a leather carry sling, shown alone"),
 (r"shooting sticks|bipod", "shooting-sticks", "wooden tripod shooting sticks"),
 (r"cleaning kit|pull through", "cleaning-kit", "a cleaning kit with rods, brushes and patches in a case"),
 (r"ear protection", "ear-protection", "electronic hearing protection earmuffs"),
 (r"shooting glasses", "shooting-glasses", "protective shooting glasses"),
 (r"lock box", "lock-box", "a small steel lock box"),
 (r"choke", "choke-tube", "a single shotgun choke tube and wrench, shown alone"),
 (r"^knife sharpener|^sharpener", "sharpener", "a compact knife sharpener"),
 (r"hunting knife|knife", "knife", "a fixed-blade hunting knife in a leather sheath"),
 (r"game bags", "game-bags", "breathable cloth game bags"),
 (r"processing kit", "processing-kit", "a butchering knife roll with saw and boning knife"),
 (r"cooler", "cooler", "a large rugged cooler"),
 (r"vacuum sealer", "vacuum-sealer", "a countertop vacuum sealer with sealed packages"),
 (r"meat grinder", "meat-grinder", "a hand-crank meat grinder"),
 (r"cape salt", "cape-salt", "a bag of salt and a scoop"),
 (r"skull mount", "skull-mount", "a bleached European deer skull mount"),
 (r"antler mount|plaque", "antler-plaque", "antlers mounted on a wooden plaque"),
 (r"tent", "tent", "a backpacking tent pitched in the forest"),
 (r"sleeping bag", "sleeping-bag", "a rolled mummy sleeping bag"),
 (r"sleeping pad", "sleeping-pad", "a rolled insulated sleeping pad"),
 (r"headlamp", "headlamp", "a headlamp with a red light mode"),
 (r"stove", "camp-stove", "a small backpacking stove with a pot"),
 (r"water filter", "water-filter", "a backcountry water filter"),
 (r"water bottle", "water-bottle", "an insulated water bottle"),
 (r"power bank|solar", "power-bank", "a rugged power bank"),
 (r"camp chair", "camp-chair", "a folding camp chair"),
 (r"tourniquet|trauma", "trauma-kit", "a compact trauma kit with tourniquet"),
 (r"first aid", "first-aid", "a red first-aid kit pouch"),
 (r"satellite messenger", "sat-messenger", "a handheld satellite messenger device"),
 (r"compass", "compass", "a baseplate compass on a topo map"),
 (r"bivy|emergency", "emergency-bivy", "a folded emergency bivy"),
 (r"fire starter", "fire-starter", "a ferro rod fire starter with tinder"),
 (r"whistle", "whistle", "a safety whistle on a lanyard"),
 (r"cellular trail camera|trail camera$|^trail camera", "trail-camera", "a trail camera strapped to a tree"),
 (r"card reader", "card-reader", "a small SD card reader"),
 (r"sd card", "sd-cards", "SD memory cards"),
 (r"batteries", "batteries", "AA and AAA batteries"),
 (r"handheld gps", "handheld-gps", "a handheld GPS unit"),
 (r"hand warmers", "hand-warmers", "hand warmer packets"),
 (r"insect|bug", "insect-repellent", "an insect head net and an unlabeled repellent bottle"),
 (r"sunscreen", "sunscreen", "an unlabeled sunscreen tube and lip balm"),
 (r"waders", "waders", "chest waders"),
 (r"blind bag", "blind-bag", "a waterproof waterfowl blind bag"),
 (r"turkey vest", "turkey-vest", "a turkey hunting vest with seat"),
 (r"frame pack|daypack|backpack", "pack", "a hunting backpack"),
 (r"trekking poles", "trekking-poles", "trekking poles"),
 (r"camera$|compact camera", "camera", "a compact camera"),
 (r"predator hunting light", "hunting-light", "a red/green hunting light"),
]
def key_for(label, query):
    txt = f"{label} | {query or ''}".lower()
    for rx, key, subj in RULES:
        if re.search(rx, txt): return key
    return None
def subjects():
    out = {}
    for rx, key, subj in RULES:
        if subj and key not in out: out[key] = subj
    return out
STYLE = ("Illustration in a rugged expedition style: muted khaki, olive drab and bronze tones with a warm sunset rim light, "
         "dark rugged canvas-textured background, the item centered and filling most of the frame, clean bold illustrated look "
         "(not a photo), square 1:1. Generic unbranded item: no text, no logos, no brand marks, no recognizable real product. "
         "No firearms, no ammunition. Subject: ")
