# Gear kit pages mirror the app's GearTemplates (TripLogic.kt). Item: (label, category, note, query or None[, apparel])
ESSENTIALS = [
 ("License & tags (printed or in app)", "Essentials", "Carry them the way your state requires. Some states need paper tags, others accept electronic ones. Check your state agency.", None),
 ("Headlamp + spare batteries", "Essentials", "You'll walk in and out in the dark. A red mode keeps your night vision.", "headlamp rechargeable"),
 ("Knife & sharpener", "Essentials", "One reliable fixed or replaceable-blade knife plus a compact sharpener.", "hunting knife sharpener"),
 ("First-aid kit", "Essentials", "Bleeding control, blister care and any personal meds.", "hunting first aid kit"),
 ("Phone + power bank", "Essentials", "Your maps, GPS return and weather live on the phone. Keep it charged and dry.", "power bank"),
 ("Water & snacks", "Essentials", "More water than you think you need, and food that doesn't crinkle.", "insulated water bottle"),
 ("Binoculars", "Optics", "You'll see more game, and see it sooner, through glass than with your eyes alone.", "hunting binoculars"),
 ("Rangefinder", "Optics", "Know your distance before the moment comes. A laser rangefinder is the standard tool.", "hunting laser rangefinder"),
]
SHARP = [("Practice ranging at the distances you expect", "Sharp Shooter", "If you use the app's Sharp Shooter camera rangefinder, calibrate it on a known distance. Its readings are estimates, not a laser.", None)]

KITS = [
 ("whitetail", "Whitetail Stand Kit", "🦌", "whitetail", "Treestand and ground-blind deer hunting close to home.", "playing-the-wind-whitetail", ["stands-blinds","scent-control","electronics-trail-cams"], [
  ("Safety harness + lifeline", "Stand", "Wear a full-body harness and stay connected from the ground up.", "tree stand safety harness"),
  ("Pull-up rope", "Stand", "Haul your bow or unloaded gun up after you're secured. Never climb with it.", "tree stand pull up rope"),
  ("Seat cushion", "Stand", "Quiet comfort keeps you on stand through the late-morning movement.", "tree stand seat cushion"),
  ("Blaze orange (confirm local rules)", "Clothing", "Requirements vary by state and season. Check with your state agency.", "blaze orange hunting vest hat", "a"),
  ("Scent-control layers", "Clothing", "Clean, stored layers you put on at the truck.", "scent control hunting clothing", "a"),
  ("Grunt call / rattling antlers", "Calls", "Useful around the rut, and best used sparingly.", "deer grunt call rattling antlers"),
  ("Drag rope & gloves", "Field", "Makes getting a deer out far easier.", "deer drag rope"),
  ("Trail cam SD cards & batteries", "Field", "Swap cards quickly and get out of the area.", "trail camera sd card"),
  ("Wind checker", "Field", "Check the wind before you pick a stand, and again once you're in it.", "wind checker powder hunting"),
 ]),
 ("elk", "Elk Backcountry Kit", "⛰️", "elk", "Pack-in mountain hunts for elk, mule deer and more.", "first-elk-hunt-checklist", ["optics","camp-lodging","game-processing","safety"], [
  ("Frame pack", "Pack", "A pack that can haul meat. Fit it to your torso length.", "hunting frame pack"),
  ("Game bags", "Pack", "Breathable bags for quartered meat.", "game bags"),
  ("Water filter", "Pack", "Filter or treat all backcountry water.", "water filter backpacking"),
  ("Trekking poles", "Pack", "They save your knees on steep descents, especially loaded with meat.", "trekking poles"),
  ("Tent & sleeping bag", "Camp", "Rated for the coldest night you can realistically expect.", "backpacking tent sleeping bag"),
  ("Layering system + rain shell", "Clothing", "Base, mid, insulation and shell. Mountain weather changes fast.", "hunting layering system rain jacket", "a"),
  ("Broken-in mountain boots", "Clothing", "Stiff, supportive boots, broken in over months, not days.", "mountain hunting boots", "a"),
  ("Spotting scope + glassing tripod", "Optics", "Most western hunts are won behind glass.", "spotting scope glassing tripod"),
  ("Bugle & cow calls", "Calls", "Cow calls are the most versatile.", "elk bugle cow call"),
  ("Satellite messenger", "Safety", "SOS and texting with no cell service.", "satellite messenger"),
  ("Offline maps / land pack downloaded", "Maps", "Download maps before you lose service. In the app, LAND packs work offline.", None),
 ]),
 ("turkey", "Spring Turkey Kit", "🦃", "turkey", "Calls, decoys and a vest for spring gobblers.", "spring-turkey-setup", ["calls-decoys","stands-blinds","clothing-boots"], [
  ("Box, slate & mouth calls", "Calls", "Bring a mix so you can change tone when a bird hangs up.", "turkey calls box slate mouth"),
  ("Locator calls (owl / crow)", "Calls", "Find gobblers without calling them toward you yet.", "owl crow locator call turkey"),
  ("Decoys", "Field", "Check your state's rules. Cover decoys when you carry them.", "turkey decoys"),
  ("Turkey vest + seat cushion", "Field", "Organizes your calls and lets you sit against a tree for an hour.", "turkey vest seat"),
  ("Face mask & gloves", "Field", "Turkeys see movement and color well. Cover your face and hands.", "camo face mask gloves", "a"),
  ("Ground blind", "Field", "Hides your movement, which is especially helpful with kids or bows.", "hunting ground blind"),
  ("Turkey choke (pattern first)", "Gun", "Pattern your shotgun with your load at known distances before the season. Buy shotshells locally.", "turkey choke tube"),
  ("Insect repellent", "Field", "Spring woods mean ticks and mosquitoes.", "insect repellent permethrin"),
 ]),
 ("waterfowl", "Waterfowl Blind Kit", "🦆", "marsh", "Marsh and field setups for ducks and geese.", "waterfowl-blind-gear-list", ["calls-decoys","dog-gear","clothing-boots"], [
  ("Waders", "Field", "Insulated chest waders for cold water. Wear a wading belt, always.", "chest waders insulated", "a"),
  ("Decoys + weights", "Field", "Match the species and the way local birds sit.", "duck decoys weights"),
  ("Blind bag", "Field", "A waterproof bag for calls, shells, snacks and your license.", "waterfowl blind bag"),
  ("Face mask & gloves", "Field", "A bare face shining up at circling birds will flare them.", "waterfowl face mask gloves", "a"),
  ("Hand warmers", "Field", "Cold, wet mornings are part of it.", "hand warmers"),
  ("Duck / goose calls", "Calls", "Practice before the season, and call less than you think.", "duck goose call"),
  ("Shotgun + shells (confirm shot-type rules)", "Gun", "Non-toxic shot is required for migratory waterfowl in the US. Buy shells locally.", None),
  ("Required stamps / permits (confirm with official sources)", "Docs", "Federal and state requirements apply. Check with official sources.", None),
  ("Dog vest & whistle", "Dog", "Neoprene vests keep retrievers warmer in cold water.", "dog neoprene hunting vest"),
 ]),
 ("safari", "Plains-Game Safari Kit", "🌅", "safari", "Travel-ready rifle kit and papers for a plains-game safari.", "first-plains-game-safari", ["firearm-accessories","clothing-boots","optics"], [
  ("Rifle + scope, zeroed with your hunting load", "Rifle", "Zero at home with the exact ammo you'll hunt with, then confirm zero on arrival.", None),
  ("Lockable hard case (check airline rules)", "Rifle", "Airline and country rules vary, so confirm with your airline and outfitter.", "hard rifle case lockable"),
  ("Ammo in airline-approved container (confirm limits)", "Rifle", "Limits and packaging rules vary by airline and country. Confirm before you book.", None),
  ("Cleaning kit", "Rifle", "A compact pull-through kit for your caliber.", "gun cleaning kit pull through"),
  ("Practice shooting off sticks before the trip", "Rifle", "Most African shots are taken off sticks, so practice from them.", "shooting sticks hunting"),
  ("Neutral khaki / olive / brown clothing (ask outfitter about camo)", "Clothing", "Some countries restrict camo. Ask your outfitter.", "khaki hunting shirt pants", "a"),
  ("Warm layer for cold mornings", "Clothing", "Winter mornings in southern Africa can be surprisingly cold.", "fleece jacket hunting", "a"),
  ("Quiet, broken-in boots", "Clothing", "Light, quiet, and broken in well before you fly.", "lightweight hunting boots", "a"),
  ("Wide-brim hat & sunglasses", "Clothing", "Sun protection all day.", "wide brim hat sunglasses", "a"),
  ("Sunscreen & lip balm", "Field", "", "sunscreen lip balm spf"),
  ("Insect repellent", "Field", "Ask your doctor or a travel clinic about other health precautions too.", "insect repellent"),
  ("Daypack", "Field", "", "hunting daypack"),
  ("Camera", "Field", "", "compact camera"),
  ("Passport + copies", "Docs", "Check how many blank pages and how much validity you need.", None),
  ("Firearm permit paperwork", "Docs", "Confirm the current process with your outfitter and official sources.", None),
  ("Travel insurance documents", "Docs", "", None),
  ("Outfitter contract & contacts", "Docs", "", None),
  ("Prescription meds in original containers", "Health", "", None),
 ]),
 ("predator", "Predator Calling Kit", "🐺", "north", "Coyote and fox calling stands, built from general predator-hunting practice.", "public-land-hunting-basics", ["calls-decoys","optics","firearm-accessories"], [
  ("Predator call (hand or electronic)", "Calls", "Rules on electronic calls vary by state and species. Check your state agency.", "predator call"),
  ("Motion decoy", "Calls", "Takes a coyote's eyes off you as it comes in.", "predator motion decoy"),
  ("Shooting sticks / bipod", "Gun", "Many predator shots are taken sitting, so a solid rest matters.", "shooting sticks bipod"),
  ("Seat cushion", "Field", "Sit still for 15 to 30 minutes per stand.", "hunting seat cushion"),
  ("Face mask & gloves", "Clothing", "Predators pick up movement and shine quickly.", "camo face mask gloves", "a"),
  ("Wind checker", "Field", "Coyotes often circle downwind. Set up so you can see that side.", "wind checker powder hunting"),
  ("Red / green hunting light (confirm night rules)", "Field", "Night-hunting rules vary widely. Confirm with your state agency.", "predator hunting light"),
 ]),
 ("northern", "Northern Moose & Bear Kit", "🫎", "north", "Boreal bush hunts: wet, cold and buggy.", "public-land-hunting-basics", ["clothing-boots","safety","game-processing"], [
  ("Warm layers + rain gear", "Clothing", "Expect wet. Bring a full rain set.", "hunting rain gear wool layers", "a"),
  ("Insulated waterproof boots", "Clothing", "Bush camps often mean muskeg and cold water.", "insulated waterproof hunting boots", "a"),
  ("Bug net & repellent", "Field", "Early-season boreal bugs are serious.", "bug head net repellent"),
  ("Game bags", "Field", "A moose is a lot of meat. Bring plenty of bags.", "game bags"),
  ("Moose call", "Calls", "", "moose call"),
  ("Passport", "Docs", "Required for crossing borders. Check the requirements for your trip.", None),
  ("Firearm paperwork (confirm with official sources)", "Docs", "Bringing firearms across a border involves specific forms. Confirm the current process with official sources.", None),
 ]),
 ("european", "European Estate Hunt Kit", "🏰", "europe", "Driven and high-seat hunts on an estate.", "rangefinding-shot-distance-basics", ["firearm-accessories","clothing-boots","optics"], [
  ("Hunting attire per estate customs (ask host)", "Clothing", "Traditions vary. Ask your host what to wear.", "loden hunting jacket", "a"),
  ("Ear protection", "Field", "Driven hunts mean a lot of shooting nearby.", "shooting ear protection electronic"),
  ("Shooting sticks / bipod", "Field", "", "shooting sticks"),
  ("Passport", "Docs", "", None),
  ("Firearm import papers (confirm with official sources)", "Docs", "Requirements differ by country. Your host or outfitter usually guides this.", None),
 ]),
 ("day-hunt", "Day-Hunt Essentials", "🎒", "camp", "The basics for any hunt.", "public-land-hunting-basics", ["safety","optics","camp-lodging"], []),
]
