# Shop departments. Each item: (card name, search query, honest "what to look for" note[, flags])
# flags: "a" = apparel (Duluth first), "d" = also show Duluth, "x" = no shop links (paperwork etc.)
DEPTS = [
 ("optics", "Optics", "🔭", "elk", "Binoculars, spotting scopes, rangefinders and the mounts that hold them steady.", [
  ("Hunting binoculars", "hunting binoculars", "8x or 10x with a 42mm objective is a common all-round choice. Try them in low light if you can; that is when you need them most."),
  ("Binocular harness", "binocular harness chest pack", "Keeps glass on your chest, out of the rain and off your neck. Quiet closures matter in a stand."),
  ("Laser rangefinder", "hunting laser rangefinder", "Check the rated range on deer-sized targets, not just reflective ones, and whether it has angle compensation for steep shots."),
  ("Spotting scope", "spotting scope hunting", "For western glassing at long distance. Angled eyepieces are easier to use from a sitting position on a tripod."),
  ("Glassing tripod", "glassing tripod binocular adapter", "A steady tripod plus a binocular adapter lets you glass far longer before your eyes tire."),
  ("Lens cleaning kit", "lens cleaning pen kit", "A lens pen and microfiber cloth. Never wipe grit off glass with your shirt."),
  ("Scope covers", "flip up scope covers", "Flip-up covers keep rain and snow off your scope lenses until the moment you need them."),
 ]),
 ("clothing-boots", "Clothing & Boots", "🥾", "north", "Layers, rain gear, boots and blaze orange that keep you out longer.", [
  ("Merino base layers", "merino wool base layer hunting", "Merino stays warm when damp and resists odor. Pick weight by how much you will be sitting versus hiking.", "a"),
  ("Insulated jacket", "insulated hunting jacket", "Quiet face fabric for stand hunting, packable synthetic or down for mountain hunts.", "a"),
  ("Rain gear", "hunting rain jacket pants", "Quiet, packable rain jacket and pants. Pit zips help on steep climbs.", "a"),
  ("Waterproof hunting boots", "waterproof hunting boots", "Break them in for weeks before the season. Insulation weight depends on how much you sit in the cold.", "a"),
  ("Rubber knee boots", "rubber knee boots hunting", "Good for wet ground, creek crossings and leaving less scent on the trail into a stand.", "a"),
  ("Blaze orange vest and hat", "blaze orange hunting vest hat", "Many states require a set amount of blaze orange during firearm seasons. Check your state agency for the rules.", "a"),
  ("Wool hunting socks", "wool hunting socks", "Bring a spare pair. Dry feet make a long day possible.", "a"),
  ("Hunting gloves", "hunting gloves", "Thin gloves for shooting and calling, plus warmer mitts or a hand muff for sitting.", "a"),
  ("Gaiters", "hunting gaiters", "Keep snow, dew and seeds out of your boots on long walks.", "a"),
 ]),
 ("stands-blinds", "Tree Stands & Blinds", "🌲", "whitetail", "Stands, ground blinds, safety harnesses and the small parts that make a setup quiet.", [
  ("Tree stand safety harness", "tree stand safety harness", "Wear a full-body harness every time you leave the ground, and check the manufacturer's expiration date.", "d"),
  ("Lifeline / safety rope", "tree stand lifeline safety rope", "Keeps you attached from the moment you leave the ground until you are back down."),
  ("Hang-on tree stand", "hang on tree stand", "Check the weight rating and follow the manufacturer's setup steps. Practice in daylight first."),
  ("Ladder stand", "ladder stand hunting", "Set it up with a partner and use every strap. It's easier for new hunters and for kids."),
  ("Climbing stand", "climbing tree stand", "Works best on straight, limb-free trees. Never climb a tree with loose bark."),
  ("Ground blind", "hunting ground blind", "Set it out days early so deer and turkeys get used to it. Brush it in with local cover."),
  ("Stand accessories", "tree stand accessory hooks bow holder", "Hooks, bow holders and pull-up ropes keep gear off the platform and within reach."),
  ("Stand seat cushion", "tree stand seat cushion", "A quiet foam cushion is the difference between sitting all morning and leaving at 9."),
 ]),
 ("calls-decoys", "Calls & Decoys", "📯", "turkey", "Grunt calls, box calls, duck calls and decoys for every season.", [
  ("Grunt call", "deer grunt call", "Soft, short grunts during the rut. Over-calling spooks more deer than it brings in."),
  ("Rattling antlers / bag", "rattling antlers deer", "Rattling works best around the pre-rut. Watch downwind, because bucks often circle."),
  ("Turkey box call", "turkey box call", "Easy to learn and loud enough to locate birds on windy days."),
  ("Turkey slate / pot call", "turkey slate pot call", "Soft yelps, clucks and purrs for close work. Bring a striker conditioner."),
  ("Turkey mouth calls", "turkey diaphragm mouth call", "Keep your hands free for the gun. Takes practice, so start before the season."),
  ("Owl / crow locator calls", "owl crow locator call turkey", "Shock-gobble birds on the roost without calling them to you."),
  ("Duck call", "duck call", "Single-reed calls are easier to learn, double-reeds are raspier. Practice with recordings."),
  ("Goose call", "goose call short reed", "Short-reed calls are versatile, but they take practice to master."),
  ("Duck decoys", "duck decoys", "Match the species you hunt and the way local birds sit. Weights and line matter as much as paint."),
  ("Turkey decoys", "turkey decoys", "Hen plus jake setups are common in spring. Never carry a decoy uncovered in the woods."),
  ("Elk bugle and cow calls", "elk bugle cow call", "Cow calls work all season. Bugles are louder and can push bulls away if used carelessly."),
  ("Predator call", "predator call rabbit distress", "Distress sounds for coyotes and foxes. Hand and electronic calls are both legal in many places; check your state."),
 ]),
 ("scent-control", "Scent Control", "🌬️", "whitetail", "Sprays, wash, storage and wind checkers. Wind is still king.", [
  ("Wind checker powder", "wind checker powder hunting", "The most useful scent tool you can carry. It shows exactly where your scent is going."),
  ("Scent elimination spray", "scent elimination spray hunting", "Spray boots and outer layers at the truck. It helps, but it doesn't beat a bad wind."),
  ("Scent-free laundry detergent", "scent free laundry detergent hunting", "Wash hunting clothes without UV brighteners or perfume."),
  ("Scent-free body wash", "scent free body wash hunting", "Shower before morning sits, especially during the rut."),
  ("Clothing storage bag / tote", "scent free clothing storage bag", "Store washed layers sealed up, and dress at the truck, not at home."),
  ("Cover scents and attractants", "deer cover scent", "Some states regulate or ban natural deer urine products because of CWD. Check your state agency before you buy or use them."),
 ]),
 ("archery", "Archery", "🏹", "elk", "Targets, releases, cases and practice gear for bowhunters.", [
  ("Archery target", "archery target block broadhead", "Use a broadhead-rated target for final tuning so your field points and broadheads hit together."),
  ("Release aid", "archery release aid", "Pick one style and practice with it all summer. Change nothing right before the season."),
  ("Bow case", "bow case hard soft", "A hard case for flights, a soft case for truck travel."),
  ("Bow sling / bow holder", "bow sling", "Keeps your hands free on long walks in."),
  ("Arrow wrench and tools", "archery broadhead wrench tool kit", "Broadhead wrench, Allen keys and string wax in one pouch."),
  ("Broadhead storage case", "broadhead case", "Protects edges and fingers. Never carry loose broadheads."),
  ("Arrow quiver", "bow quiver", "Practice with the quiver on if you hunt with it on, because it changes how the bow balances."),
 ]),
 ("firearm-accessories", "Firearm Accessories", "🎯", "safari", "Cases, slings, shooting sticks, cleaning and ear protection. Accessories only.", [
  ("Hard rifle case", "hard rifle case lockable", "Lockable hard cases are generally required for flying with firearms. Always confirm the airline's own rules."),
  ("Soft rifle case", "soft rifle case", "Padded protection for truck and ATV travel."),
  ("Rifle sling", "rifle sling hunting", "A good sling frees your hands on long walks and can steady a shot."),
  ("Shooting sticks", "shooting sticks hunting", "Standard on African safaris and great everywhere else. Practice off them before your trip."),
  ("Bipod", "rifle bipod", "Steadies prone and bench shots. Check that it fits your rifle's mounting point."),
  ("Gun cleaning kit", "gun cleaning kit", "A caliber-specific rod or pull-through, patches, solvent and oil."),
  ("Ear protection", "shooting ear protection electronic", "Electronic muffs let you hear normal sounds while blocking gunshots. Wear them every time you practice."),
  ("Shooting glasses", "shooting glasses", "Eye protection at the range, and in the duck blind too."),
  ("Gun safe / lockbox", "gun lock box", "Secure storage at home and on the road."),
 ]),
 ("game-processing", "Game Processing", "🔪", "camp", "Knives, game bags, coolers, grinders and taxidermy supplies for after the harvest.", [
  ("Hunting knife", "hunting knife fixed blade", "A sharp, simple blade you can clean easily. Many hunters carry a replaceable-blade knife as a backup."),
  ("Knife sharpener", "knife sharpener field", "A compact field sharpener plus a better one at camp."),
  ("Game bags", "game bags", "Breathable bags keep meat clean and cooling. They're essential for quartering elk."),
  ("Field dressing gloves", "field dressing gloves", "Long nitrile gloves for cleaner, safer field dressing."),
  ("Game processing kit", "game processing kit", "Saw, boning knife and gut hook in one roll. Handy for camp butchering."),
  ("Large cooler", "large cooler hunting", "Size it for a quartered animal plus ice. Pre-chill it before the trip."),
  ("Vacuum sealer", "vacuum sealer", "Vacuum-sealed meat keeps much longer in the freezer."),
  ("Meat grinder", "meat grinder", "For burger and sausage at home. Keep the parts cold while you grind."),
  ("Cape salt for taxidermy", "taxidermy cape salt", "If you plan a mount, talk to your taxidermist first. They'll tell you how they want the cape handled."),
  ("European skull mount kit", "european skull mount kit", "A DIY project for winter. Follow the kit's safety notes."),
  ("Antler mount plaque kit", "antler mount plaque kit", "A simple way to display antlers without a full mount."),
 ]),
 ("camp-lodging", "Camp & Lodging Gear", "⛺", "camp", "Tents, sleep systems, camp kitchen, and lodging search for your hunt area.", [
  ("Tent", "backpacking tent 2 person", "Pack-in hunts need weight-conscious tents, and base camps can go bigger. Practice pitching at home.", "d"),
  ("Sleeping bag", "sleeping bag cold weather", "Pick by realistic temperature ratings for the coldest night you expect.", "d"),
  ("Sleeping pad", "insulated sleeping pad", "Insulation from the ground matters as much as the bag. Check the R-value."),
  ("Headlamp", "headlamp rechargeable", "A red-light mode keeps your night vision. Bring spare batteries.", "d"),
  ("Camp stove", "backpacking stove", "Compact stoves for the backcountry, two-burner stoves for base camp."),
  ("Water filter", "water filter backpacking", "Filter or treat all backcountry water."),
  ("Power bank", "power bank solar", "Phone maps, GPS and headlamps all run on batteries. Keep a charged bank in a dry bag.", "d"),
  ("Camp chair", "camp chair", "Small luxury, big morale.", "d"),
 ]),
 ("safety", "Safety", "🦺", "north", "First aid, navigation backup and emergency communication.", [
  ("First-aid kit", "hunting first aid kit", "Build it around bleeding control and blisters, and know how to use what's in it.", "d"),
  ("Tourniquet / trauma kit", "tourniquet trauma kit", "Take a bleeding-control class. A tool you can't use won't help.", "d"),
  ("Satellite messenger", "satellite messenger", "Two-way texting and SOS where there's no cell service. Check the subscription requirements."),
  ("Compass", "baseplate compass", "A backup for when the phone dies. Learn to use it with a paper map."),
  ("Emergency blanket / bivy", "emergency bivy", "Weighs almost nothing and can save a cold night out."),
  ("Fire starter", "fire starter kit waterproof", "Waterproof matches, a ferro rod and tinder in a dry bag.", "d"),
  ("Whistle", "safety whistle", "Three blasts carry farther than your voice and take far less energy."),
  ("Blaze orange for the walk out", "blaze orange hat", "Even in seasons where it isn't required, orange is a smart choice when you're dragging a deer out.", "a"),
 ]),
 ("electronics-trail-cams", "Electronics & Trail Cams", "📷", "whitetail", "Trail cameras, SD cards, batteries, GPS and headlamps.", [
  ("Trail camera", "trail camera", "Cellular cams save trips into the woods. Standard cams cost less but need SD card pulls. Check your state's rules on cameras and on public land."),
  ("Cellular trail camera", "cellular trail camera", "Check the coverage at your spot and the data plan cost before you buy."),
  ("Trail cam SD cards", "trail camera sd card", "Use the card size and speed class the camera maker recommends. Carry spares."),
  ("AA / AAA batteries", "AA AAA batteries lithium", "Lithium batteries handle cold far better than alkaline."),
  ("Trail cam mount / lock box", "trail camera mount lock box", "Mounts help you aim. Lock boxes and cables deter theft."),
  ("SD card reader for phone", "sd card reader usb c", "Check pictures in the field without hauling the camera home."),
  ("Handheld GPS", "handheld gps hunting", "Optional backup for your phone app, especially on long backcountry trips."),
 ]),
 ("dog-gear", "Dog Gear", "🐕", "marsh", "Vests, whistles, first aid and training gear for hunting dogs.", [
  ("Dog neoprene vest", "dog neoprene hunting vest", "Keeps retrievers warmer in cold water. Measure your dog's chest before ordering."),
  ("Dog whistle", "dog training whistle", "A consistent whistle makes handling easier at a distance."),
  ("Dog blaze orange vest", "dog blaze orange vest", "Makes your dog visible to other hunters during upland and deer seasons."),
  ("Dog first-aid kit", "dog first aid kit", "Vet wrap, saline, booties and tweezers. Ask your vet what else to carry."),
  ("Dog boots", "dog boots hunting", "Protect paws on rough ground. Let your dog get used to them before the season."),
  ("Retriever training dummies", "retriever training dummy", "Off-season training builds better retrieves in the blind."),
  ("Dog stand / blind platform", "dog stand duck blind", "Gets your dog out of cold water while you wait for birds."),
  ("GPS dog tracking collar", "gps dog tracking collar", "Check the range, the rules on electronic collars in your state, and whether it needs a subscription."),
 ]),
]

# Shop-by-hunt tiles -> gear kit pages
HUNTS = [
 ("whitetail", "Whitetail", "🦌", "whitetail"),
 ("elk", "Elk", "⛰️", "elk"),
 ("turkey", "Spring Turkey", "🦃", "turkey"),
 ("waterfowl", "Waterfowl", "🦆", "marsh"),
 ("safari", "Plains-Game Safari", "🌅", "safari"),
 ("predator", "Predator", "🐺", "north"),
 ("northern", "Moose & Bear", "🫎", "north"),
 ("european", "European Estate", "🏰", "europe"),
 ("day-hunt", "Day-Hunt Essentials", "🎒", "camp"),
]

# GearHub.kt rows (season essentials / restock / after harvest)
SEASON = [("Waterproof hunting boots","waterproof hunting boots","a"),("Rain gear","hunting rain gear","a"),("Scent control spray","scent elimination spray hunting",""),
          ("Binoculars","hunting binoculars",""),("Tree stand safety harness","tree stand safety harness",""),("Game bags","game bags",""),("Headlamp","headlamp rechargeable",""),
          ("Merino base layer","merino wool base layer hunting","a"),("Hand warmers","hand warmers","")]
RESTOCK = [("Broadheads","broadheads",""),("AA / AAA batteries","AA AAA batteries lithium",""),("Scent elimination spray","scent elimination spray hunting",""),
           ("Hand warmers","hand warmers",""),("Trail cam SD cards","trail camera sd card",""),("Field dressing gloves","field dressing gloves",""),("Wind checker","wind checker powder hunting","")]
HARVEST = [("Game processing kit","game processing kit",""),("Game bags","game bags",""),("Vacuum sealer","vacuum sealer",""),("Meat grinder","meat grinder",""),
           ("Large cooler","large cooler hunting",""),("Cape salt for taxidermy","taxidermy cape salt",""),("European skull mount kit","european skull mount kit",""),("Antler mount plaque kit","antler mount plaque kit","")]
